from .nodes_claude_api import NODE_CLASS_MAPPINGS as CLAUDE_MAPPINGS
from .nodes_claude_api import NODE_DISPLAY_NAME_MAPPINGS as CLAUDE_DISPLAY
from .nodes_grok_api import NODE_CLASS_MAPPINGS as GROK_MAPPINGS
from .nodes_grok_api import NODE_DISPLAY_NAME_MAPPINGS as GROK_DISPLAY

NODE_CLASS_MAPPINGS = {**CLAUDE_MAPPINGS, **GROK_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**CLAUDE_DISPLAY, **GROK_DISPLAY}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
